// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP6iaPW-pGFWucwtRXVPM-xE1YQrqS5ac',
    appId: '1:868206696956:web:504b7111a9166f4e7fba79',
    messagingSenderId: '868206696956',
    projectId: 'totalx-9ba0d',
    authDomain: 'totalx-9ba0d.firebaseapp.com',
    storageBucket: 'totalx-9ba0d.appspot.com',
    measurementId: 'G-NXCJZD0YPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqpxntRIDerwsF2cRoc2FfrB1TjsuQoMI',
    appId: '1:868206696956:android:2e0112859adba1ad7fba79',
    messagingSenderId: '868206696956',
    projectId: 'totalx-9ba0d',
    storageBucket: 'totalx-9ba0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYAmb29nNL-ZI8XL3g8_hHoE2HotQeyhQ',
    appId: '1:868206696956:ios:93f76ee9406e69177fba79',
    messagingSenderId: '868206696956',
    projectId: 'totalx-9ba0d',
    storageBucket: 'totalx-9ba0d.appspot.com',
    iosBundleId: 'com.example.totalxMachineTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYAmb29nNL-ZI8XL3g8_hHoE2HotQeyhQ',
    appId: '1:868206696956:ios:aef5177a59f8a75d7fba79',
    messagingSenderId: '868206696956',
    projectId: 'totalx-9ba0d',
    storageBucket: 'totalx-9ba0d.appspot.com',
    iosBundleId: 'com.example.totalxMachineTask.RunnerTests',
  );
}
